### ISSUE TITLE
No license in repository

### ISSUE THREAD

**Issue by l3d00m** [Aceinna/gnss-ins-sim#14]
Hi,

thanks for the great project, it's really helpful for me. I have a q though, is it possible for you guys to add a offcial license?

In your setup.py you state MIT License, but I couldn't find it in the repository. Here's a tutorial: https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository 

Thanks again :)

**Comment by dxg-aceinna** [comment]
Hi,

Thank you for your advice. The MIT license is added.

Dong

**Comment by l3d00m** [comment]
Thanks a lot for that (and the helpful project of course)!
