### ISSUE TITLE
Hard dependency on matplotlib even if you don't need to plot graphs

### ISSUE THREAD

**Issue by TechArtistG** [Aceinna/gnss-ins-sim#17]
From looking at the code matplotlib is minimally used and only to show graph plots.  However matplotlib drags in a lot of dependencies causing issues.

Be good if matplotlib was not referenced directly inside core gnss-ins-sim modules.  Maybe a separate graphing module.

**Comment by dxg-aceinna** [comment]
Thanks for your suggestions. I will consider this.
