### ISSUE TITLE
No Rate Random Walk modeled in `pathgen.py`, right?

### ISSUE THREAD

**Issue by astroHaoPeng** [Aceinna/gnss-ins-sim#23]
RE: https://github.com/Aceinna/gnss-ins-sim/blob/master/gnss_ins_sim/pathgen/pathgen.py

It looks like to me you this simulation only considers `constant bias` (or `turn-on bias`; `static bias` in your code at line 520), `bias instability` (`bias drifting` in your code at line 522), and `angle random walk` (`white noise` in your code at line 524). 

I have a question that why `rate random walk` is not considered in the simulation. Does it have a neglectable effect on the gyro error?
According to these references, it seems `rate random walk` also has a considerable effect on the simulation of the gyro error:
1. Jay A. Farrell, Felipe O. Silva, Farzana Rahman, and Jan Wendel, “IMU Error State Modeling for State Estimation and Sensor Calibration: A Tutorial”, May 2019. [[Link]](https://escholarship.org/uc/item/1vf7j52p).
2. Elder M. Hemerly, “MEMS IMU stochastic error modelling”, Systems Science & Control Engineering, vol. 5, Jan. 2017, pp. 1–8.
3. Vaibhav Saini, S C Rana, and MM Kuber, “Online Estimation of State Space Error Model for MEMS IMU”, Journal of Modelling and Simulation of Systems, vol. 1, 2010, pp. 219--225.

Also, do you have a good reference to simulate the `bias instability` as a white noise sequence, rather then a random walk sequence, when there is no `correlation` input (line 558 in the code)? I think it is improper as suggested by the above references 2 and 3.

**Comment by dxg-aceinna** [comment]
Hi astroHaoPeng,

Different applications care about different specs. In your application, do you really care about rate random walk? could you observe and characterize rate random walk in the sensor you are using? I generally use gyro combined with other sensors (typicall GNSS), I don't care about rate random walk at all. Of course, if you are studying the theory, everything matters.

For modellling bias isntability, please see another open issue: https://github.com/Aceinna/gnss-ins-sim/issues/19
I think ace-e4s is right and am waiting for a pull request.

Actaully, there are other error sources that may have larger effects, including scale factor error, non-linearity, non-orthogonality, installation error, g-sensitivity, bias change with temperature,... Such error sources are not included in the model, either. You can add these according to your application.
