### ISSUE TITLE
odo 写成 gps

### ISSUE THREAD

**Issue by BriFuture** [Aceinna/gnss-ins-sim#28]
https://github.com/Aceinna/gnss-ins-sim/blob/d4b51d1c40a29e8562471d1c91b17102aec94d8c/gnss_ins_sim/sim/imu_model.py#L306

https://github.com/Aceinna/gnss-ins-sim/blob/d4b51d1c40a29e8562471d1c91b17102aec94d8c/gnss_ins_sim/sim/imu_model.py#L313

**Comment by dxg-aceinna** [comment]
多谢，已经修复。
