### ISSUE TITLE
a question for imu model parameter?

### ISSUE THREAD

**Issue by rainlord** [Aceinna/gnss-ins-sim#30]
hello,dear@Aceinna
      i have same question about the imu model?
      1.which parameter is the Gaussian white noise ？  
      2.The imu model parameter which means in  discrete sample case or in continuous sample case？ thanks alot!

**Comment by dxg-aceinna** [comment]
hello rainlord,

1. ARW or VRM corresponds to the white noise of gyro or accel.
2. discrete sample.

**Comment by rainlord** [comment]
thanks alot！@dxg-aceinna
