### ISSUE TITLE
Computation of w_nb_n in function calc_true_sensor_output

### ISSUE THREAD

**Issue by rodrigo-moliveira** [Aceinna/gnss-ins-sim#33]
Hello.

I noticed a slight disparity between the computation of vector `w_nb_n` (angular rotation vector from b to n expressed in n frame) in function `calc_true_sensor_output` of file pathgen.py comparing to the formulae that I found in various theory sources.

It seems that you are interpreting the result as `w_nb_n`, but these authors say that this vector is actually `w_nb_b` (that is, expressed in b frame coordinates).

![imagem](https://user-images.githubusercontent.com/56005315/160661106-b5855135-5b8c-4590-9a81-1dede136e8b3.png)

Sources:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.668.1629&rep=rep1&type=pdf  Eq.9  , 
https://www.atlantis-press.com/article/25897503.pdf Eq. 18, 
Springer Handbook of Global Navigation Satellite Systems, Chapter 28, Eqs (28.21)-(28.23)

Am I missing something, or is this correct?

Thank you for your time

**Comment by dxg-aceinna** [comment]
You can find `c_n2b` in the document [4.2.1 Rotation](https://github.com/Aceinna/gnss-ins-sim/blob/master/gnss_ins_sim/docs/gnss-ins-sim-doc.md#421-rotation)

**Comment by rodrigo-moliveira** [comment]
Indeed I tried what you proposed (compute w_nb_b and then rotate it with c_nb.T) and I obtained the same result.

Thank you for your clarification :)

I'll close the issue.
