### ISSUE TITLE
Command Type 1 reference frame

### ISSUE THREAD

**Issue by blj39** [Aceinna/gnss-ins-sim#34]
Hello,

Thank you for sharing this toolbox. I was wondering: what are reference frames (world vs body) for command type 1 inputs? It seems to me that the rotation rate inputs are in world frame while the acceleration is in a body-fixed frame; is that correct.

For reference, I am attempting to generate IMU data for a known trajectory, given as NED positions and orientations. I have differentiated to get velocity, acceleration, and rotation rates, and use the attitude to transform the accelerations into body-frame. After disabling the filter on the inputs, this seems to give me the correct reference accelerations (ref_accel), rotation rates (ref_gyro), and attitudes (ref_att_euler) but the outputs for position (ref_pos) and velocity (ref_vel) do not match the source data.

I'm trying to track down what I am doing incorrect, and would appreciate any advice.

**Comment by dxg-aceinna** [comment]
Hello,

1. For command type 1, the rotation rate is actually "Euler angle change rate". Please notice the difference between the two.
2. If  ref_accel, ref_gyro and ref_att_euler are all correct, I think you can check the way how IMU is integrated.
3. If ref_pos and ref_vel only show a little difference from the source data, I think you can increase the sampling rate to see if the difference is from numerical difference.
