### ISSUE TITLE
真实加速度测量值生成问题

### ISSUE THREAD

**Issue by cdhuanghl** [Aceinna/gnss-ins-sim#44]
在pathgen.py文件中的函数 def calc_true_sensor_output(pos_n, vel_b, att, c_nb, vel_dot_b, att_dot, ref_frame, g) 中
406~411行代码如下：
    # Gyroscope output
    gyro = c_nb.T.dot(w_nb_n + w_en_n + w_ie_n)
    # Acceleration output
    w_ie_b = c_nb.T.dot(w_ie_n)
    acc = vel_dot_b + attitude.cross3(w_ie_b+gyro, vel_b) - c_nb.T.dot(gravity)
    return acc, gyro, vel_dot_n, pos_dot_n

在计算真实加速度时，这一项

 attitude.cross3(w_ie_b+gyro, vel_b) 

中的gyro项里面包含了w_nb_n，是否合理？

**Comment by dxg-aceinna** [comment]
我已经不记得具体的推导过程了，大概思路如下：
1. 一般INS算法中的速度都是相对于地球的速度；
2. 一般INS算法中都会提到上述速度在NED或ENU坐标系的求导，将其导数与各种角速度、加速度计测量输出以及local gravity联系起来；
3. 这里的推导应该是上述速度在载体坐标系内的求导。

关于陀螺输出，其是本体坐标系相对于惯性坐标系的角速度在本体坐标系下表示，应当包含本体系相对于导航系、导航系相对于地固系以及地固系相对于惯性系。
