### ISSUE TITLE
Issue with mid-accuracy

### ISSUE THREAD

**Issue by layssi** [Aceinna/gnss-ins-sim#48]
If you run   " demo_free_integration_long_time.py" with mid-accuracy, you get odd results.

#imu_err = 'low-accuracy'
#imu_err = 'high-accuracy'
imu_err = 'mid-accuracy'
# generate GPS and magnetometer data
imu = imu_model.IMU(accuracy=imu_err, axis=6, gps=False)

**Comment by dxg-aceinna** [comment]
If you mean the results diverge by "odd results", I think that's normal for a long time free integration with IMU error enabled.
