### ISSUE TITLE
能否使用ENU坐标系输出？

### ISSUE THREAD

**Issue by JiaqiangZhang** [Aceinna/gnss-ins-sim#49]
请问一下可以输出ENU坐标系的数据吗？如果可以的话需要怎么设置呢？

感觉要对加速度计、陀螺仪和磁力计的数据进行坐标变换，交换x和y的数据，并对z轴数据取反。我对导航的理解还很浅，如果不对还望您谅解。

十分感谢！

**Comment by JiaqiangZhang** [comment]
感谢回复！

还有一个问题，对于body系，FRD和RFU的变换和NED到ENU的变换也是类似的吧

**Comment by dxg-aceinna** [comment]
都是类似的。

**Comment by JiaqiangZhang** [comment]
好的，谢谢
